replicaCount: 2

image:
  repository: ghcr.io/kytaalok/sample-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: sample-api.localdev.me
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: sample-api-tls
    clusterIssuer: selfsigned-cluster-issuer

externalSecret:
  enabled: true
  refreshInterval: 1h
  store:
    kind: ClusterSecretStore
    name: shared-secrets-store
  targetSecretName: sample-api-runtime
  data:
    - secretKey: API_KEY
      remoteRef:
        key: sample-api-runtime
        property: API_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: sample-api-runtime
        property: DATABASE_URL

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 65

keda:
  enabled: true
  minReplicas: 2
  maxReplicas: 12
  timezone: Europe/Moscow
  scaleUpStart: "0 8 * * 1-5"
  scaleUpEnd: "0 20 * * 1-5"

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

serviceAccount:
  create: true
  name: ""
