apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sample-api.fullname" . }}-allow-http
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sample-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: dev-apps
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
